Practice2
ne1true/CatsList pull request #1
Opened 2021-06-26 18:10 UTC by ne1true

2021-06-29 09:53 UTC, vasilevkin requested changes
good start.
continue with implementation.

2021-06-29 09:53 UTC, vasilevkin commented on CatsList/CatsListTableViewController.swift
> +        if indexPath.section == 0 {
better use switch

2021-06-29 09:53 UTC, vasilevkin commented on CatsList/NetworkManager/NetworkManager.swift
> +        session.configuration.timeoutIntervalForRequest = 30
move magic numbers into constants

2021-06-29 09:53 UTC, vasilevkin commented on CatsList/NetworkManager/NetworkManager.swift
> +                    print("Timeout error!")
show these errors to user

2021-07-31 15:36 UTC, ne1true commented on CatsList/CatsListTableViewController.swift
> +        if indexPath.section == 0 {
done in pr4

2021-07-31 15:36 UTC, ne1true commented on CatsList/NetworkManager/NetworkManager.swift
> +                    print("Timeout error!")
done in pr4

2021-07-31 15:36 UTC, ne1true commented on CatsList/NetworkManager/NetworkManager.swift
> +                    print("Timeout error!")
done in pr4

2021-07-31 15:36 UTC, ne1true commented on CatsList/NetworkManager/NetworkManager.swift
> +        session.configuration.timeoutIntervalForRequest = 30
done in pr4

2021-07-31 15:37 UTC, merged