Practice3
ne1true/CatsList pull request #2
Opened 2021-06-29 18:37 UTC by ne1true

2021-06-30 08:35 UTC, vasilevkin requested changes
pretty much good. But pay attention to details.

2021-06-30 08:35 UTC, vasilevkin commented on CatsList/CatsList/CatsListTableViewController.swift
> +            if errorDescription != nil {
if let errorDescription ...

better use this instead of nil comparison.

2021-06-30 08:35 UTC, vasilevkin commented on CatsList/CatsList/CatsListViewModel.swift
> +            guard let loadCatsList = loadCatsList else { return }
logic is correct, but it should load all items in loadCatsList
just repeat this pattern for all items, not only first 7

2021-06-30 08:35 UTC, vasilevkin commented on CatsList/CatsList/CollectionTableViewCell/CollectionCell.xib
> +<?xml version="1.0" encoding="UTF-8"?>
check labels, text should be displayed completely.
and not truncated or overflow screen
and also align text and images for all cell types.

![2021-06-30_11-31-09](https://user-images.githubusercontent.com/13586523/123928555-b03c5d80-d996-11eb-883d-081d2240f2dc.png)

2021-06-30 08:35 UTC, vasilevkin commented on CatsList/StarWars/StarWarsCell/StarWarsCell.xib
> +<?xml version="1.0" encoding="UTF-8"?>
ui should look correctly on devices with a small screen size.

![2021-06-30_11-33-30](https://user-images.githubusercontent.com/13586523/123928923-01e4e800-d997-11eb-9374-b14a138a2cbe.png)

2021-06-30 08:35 UTC, vasilevkin commented on CatsList/StarWars/StarWarsDetailViewController.swift
> +    @IBOutlet weak var lblName: UILabel!
better name it NameLabel and all other similar

2021-06-30 08:35 UTC, vasilevkin commented on CatsList/StarWars/StarWarsSearchViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
move outlets on the top of the class

2021-06-30 17:03 UTC, ne1true commented on CatsList/CatsList/CatsListTableViewController.swift
> +            if errorDescription != nil {
done

2021-06-30 17:03 UTC, ne1true commented on CatsList/CatsList/CatsListViewModel.swift
> +            guard let loadCatsList = loadCatsList else { return }
done

2021-06-30 17:03 UTC, ne1true commented on CatsList/CatsList/CollectionTableViewCell/CollectionCell.xib
> +<?xml version="1.0" encoding="UTF-8"?>
done

2021-06-30 17:03 UTC, ne1true commented on CatsList/StarWars/StarWarsCell/StarWarsCell.xib
> +<?xml version="1.0" encoding="UTF-8"?>
done

2021-06-30 17:04 UTC, ne1true commented on CatsList/StarWars/StarWarsSearchViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
done

2021-06-30 17:04 UTC, ne1true commented on CatsList/StarWars/StarWarsDetailViewController.swift
> +    @IBOutlet weak var lblName: UILabel!
done

2021-07-07 17:50 UTC, alekseykorol commented on CatsList/CatsList/CatsListTableViewController.swift
> +            let cell = tableView.dequeueReusableCell(withIdentifier: reusableCellIdentifier, for: indexPath) as! GorisontalTableViewCell
Force casts should be avoided (Force Cast).

Please check project with SwiftLint and fix warnings.
("swiftlint autocorrect" can also be used)

2021-07-07 17:51 UTC, alekseykorol commented on CatsList/CatsList/CatsListTableViewController.swift
> +        case 0:
Please add enum for sections

2021-07-07 17:55 UTC, alekseykorol commented on CatsList/CatsList/CollectionTableViewCell/CollectionTableViewCell.swift
> +    @IBOutlet weak var collectionView: UICollectionView!
IBOutlets should be private to avoid leaking UIKit to higher layers ([Private Outlet](https://realm.github.io/SwiftLint/private_outlet.html))

2021-07-26 08:15 UTC, vasilevkin requested changes

2021-07-26 08:15 UTC, vasilevkin commented on CatsList.xcodeproj/xcuserdata/sergey.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +<?xml version="1.0" encoding="UTF-8"?>
Do not include this file into pr

2021-07-26 08:15 UTC, vasilevkin commented on CatsList/StarWars/StarWarsSearchViewController.swift
> +        100
try to use constants instead of magic numbers

2021-07-31 15:37 UTC, ne1true commented on CatsList/CatsList/CatsListTableViewController.swift
> +            let cell = tableView.dequeueReusableCell(withIdentifier: reusableCellIdentifier, for: indexPath) as! GorisontalTableViewCell
done in pr4

2021-07-31 15:37 UTC, ne1true commented on CatsList/CatsList/CatsListTableViewController.swift
> +        case 0:
done in pr4

2021-07-31 15:37 UTC, ne1true commented on CatsList/CatsList/CollectionTableViewCell/CollectionTableViewCell.swift
> +    @IBOutlet weak var collectionView: UICollectionView!
done in pr4

2021-07-31 15:37 UTC, ne1true commented on CatsList.xcodeproj/xcuserdata/sergey.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +<?xml version="1.0" encoding="UTF-8"?>
done in pr4

2021-07-31 15:37 UTC, ne1true commented on CatsList/StarWars/StarWarsSearchViewController.swift
> +        100
done in pr4

2021-07-31 15:41 UTC, merged