Practice6
ne1true/CatsList pull request #5
Opened 2021-08-25 16:03 UTC by ne1true

additional: share news, work without internet connection, dark theme

2021-09-02 08:31 UTC, vasilevkin requested changes
good job, but there is a room for non mandatory improvements

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/DataManager/DataManagerImpl.swift
> +        fetchRequest.predicate = NSPredicate(format: "url = %@", url)
better to move predicate to a constant

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/DataManager/DataManagerImpl.swift
> +            if fetchResult.count > 0 {
do not compare to magic number, better use .isNotEmpty or something similar

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/Dogs&CatsList/DogsCatsView/DogsCatsCollectionViewController.swift
> +        if (tabBarController?.viewControllers?.indices.contains(menuItem)) != nil {
do not compare to nil

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/Dogs&CatsList/DogsCatsView/SquareCollectionCell/SquareCollectionViewCell.swift
> +protocol CellDidSelectDelegate: AnyObject {
try to avoid AnyObject if possible

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/Endpoints/NewsPaperEndpoint.swift
> +        let requestCountry = country ?? "us"
better to move default value to some constant

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/Extensions/Date+Extension.swift
> +        case ...3600:
do not use magic numbers

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/Extensions/Date+Extension.swift
> +        let formatterPrint = DateFormatter()
creating DateFormatter() is quite heavy, try to create it one time and reuse when possible

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/Extensions/String+Extension.swift
> +        let formatter = DateFormatter()
creating DateFormatter() is quite heavy, try to create it one time and reuse when possible

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/Extensions/UIButton+extension.swift
> +        let radians = angle / 180.0 * CGFloat(Double.pi)
do not use magic numbers. try to search for appropriate system's constants

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/Extensions/UIImage+Extension.swift
> +        let xSize = (refWidth - size.width) / 2
do not use magic numbers

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/Extensions/UIPickerView+Extension.swift
> +        if self.subviews.count <= 2 {
try to avoid magic numbers

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/Extensions/UIPickerView+Extension.swift
> +            }
think not only about a golden path,
but what will happen if count not equal 2
how it works now and how it should work

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/NewsPaper/DetailVC/NewsPaperDetailViewController.swift
> +                let loadImage = loadImage ?? UIImage(named: "no-image")
move default image to some constant

2021-09-02 08:31 UTC, vasilevkin commented on CatsList/NewsPaper/NewsPaperVC/FilterVC/NewsPaperFilterModel.swift
> +    case country = 0, category
do not use magic numbers

2021-09-12 14:18 UTC, ne1true commented on CatsList/CatsList/CatsListView/CatsListTableViewController.swift
> +        if (tabBarController?.viewControllers?.indices.contains(menuItem)) != nil {
done

2021-09-12 14:18 UTC, ne1true commented on CatsList/DataManager/DataManagerImpl.swift
> +        let dateSort = NSSortDescriptor(key: "publishedAt", ascending: false)
done (full re-write)

2021-09-12 14:19 UTC, ne1true commented on CatsList/DataManager/DataManagerImpl.swift
> +                let title = bookMark.value(forKey: "title") as? String
done (full re-write)

2021-09-12 14:19 UTC, ne1true commented on CatsList/Extensions/UIImage+Extension.swift
> +        let xSize = (refWidth - size.width) / 2
done

2021-09-12 14:19 UTC, ne1true commented on CatsList/NewsPaper/NewsPaperVC/FilterVC/NewsPaperFilterModel.swift
> +    case country = 0, category
done

2021-09-12 14:19 UTC, ne1true commented on CatsList/DataManager/DataManagerImpl.swift
> +        fetchRequest.predicate = NSPredicate(format: "url = %@", url)
done

2021-09-12 14:19 UTC, ne1true commented on CatsList/Dogs&CatsList/DogsCatsView/DogsCatsCollectionViewController.swift
> +        if (tabBarController?.viewControllers?.indices.contains(menuItem)) != nil {
done

2021-09-12 14:19 UTC, ne1true commented on CatsList/Dogs&CatsList/DogsCatsView/SquareCollectionCell/SquareCollectionViewCell.swift
> +protocol CellDidSelectDelegate: AnyObject {
done (full re-write)

2021-09-12 14:20 UTC, ne1true commented on CatsList/Endpoints/NewsPaperEndpoint.swift
> +        let requestCountry = country ?? "us"
done

2021-09-12 14:20 UTC, ne1true commented on CatsList/Extensions/Date+Extension.swift
> +        let formatterPrint = DateFormatter()
done (?)

2021-09-12 14:20 UTC, ne1true commented on CatsList/Extensions/UIButton+extension.swift
> +        let radians = angle / 180.0 * CGFloat(Double.pi)
done

2021-09-12 14:20 UTC, ne1true commented on CatsList/Extensions/UIPickerView+Extension.swift
> +        if self.subviews.count <= 2 {
done

2021-09-12 14:21 UTC, ne1true commented on CatsList/Extensions/UIPickerView+Extension.swift
> +            }
done

2021-09-12 14:21 UTC, ne1true commented on CatsList/NewsPaper/DetailVC/NewsPaperDetailViewController.swift
> +                let loadImage = loadImage ?? UIImage(named: "no-image")
done

2021-09-13 12:01 UTC, vasilevkin approved these changes
LGTM

2021-09-22 12:20 UTC, merged